In [1]:
# Import dependencies
import pandas as pd

In [2]:
# Read file into DataFrame
filename = "../Resources/ratings_and_sentiments.csv"
coffee_shop_ratings_df = pd.read_csv(filename)
coffee_shop_ratings_df .head()

FileNotFoundError: [Errno 2] No such file or directory: '../Resources/ratings_and_sentiments.csv'

In [37]:
# Find all reviews with a number rating greater than or equal to 4.
coffee_shop_ratings_df.loc[coffee_shop_ratings_df["num_rating"] >= 4,"review_text"]

0       11/25/2016 1 check-in Love love loved the vibe...
1       12/2/2016 Listed in Date Night: Austin, vibe i...
2       11/30/2016 1 check-in Listed in food seating I...
4       12/3/2016 1 check-in They are location within ...
5       11/20/2016 1 check-in Very cute cafe! I think ...
                              ...
7610    3/1/2016 Great food! I haven't had a food I di...
7611    2/19/2015 I actually step into this restaurant...
7612    1/21/2016 Ok, The coffeeing seating IS awesome...
7613    4/30/2015 Loved coming here for tea, and the v...
7615    5/23/2015 I finally stopped in for food with m...
Name: review_text, Length: 6140, dtype: object

In [46]:
# Find all the coffee shops with a overall sentiment greater than or equal to 4.
coffee_shop_ratings_df.loc[coffee_shop_ratings_df["overall_sent"] >= 4,"coffee_shop_name"]

0            The Factory - Cafe With a Soul
233                Mozart's Coffee Roasters
931                  Venezia Italian Gelato
1101         The Factory - Cafe With a Soul
1466               Figure 8 Coffee Purveyors
1591                 MaГ±ana Coffee & Juice
2008         The Factory - Cafe With a Soul
2213                      Flat Track Coffee
2595                 Flightpath Coffeehouse
2681    Third Coast Coffee Roasting Company
2831                             Dolce Neve
3051                                Halcyon
3106         The Factory - Cafe With a Soul
3390              Arturo's Underground Cafe
3425              Arturo's Underground Cafe
3787                       Lucky Lab Coffee
4137                                Halcyon
4419                               Tea Haus
4515                    Friends & Neighbors
4530                      Sorrento's Coffee
4576                      Sorrento's Coffee
4771                 Venezia Italian Gelato
5086                                Halcyon
5612                          Dominican Joe
5998                        La Tazza Fresca
6428            Strange Brew, Austin Coffee
6836                                    Teo
6963                          La Patisserie
6999                        My Sweet Austin
7099                              Cafe Java
7148                       Russell's Bakery
7558                      The Steeping Room
Name: coffee_shop_name, dtype: object

In [48]:
# Return the count of the above query.
len(rate_df[(rate_df['overall_sent'] >=4) & (rate_df['num_rating'] > 4)])

32

In [50]:
# Change the name of the review_text column to review
coffee_shop_ratings_df = coffee_shop_ratings_df.rename(columns={"review_text":"review"})
coffee_shop_ratings_df.head()

,coffee_shop_name,review,rating,num_rating,cat_rating,bool_HIGH,overall_sent,vibe_sent,tea_sent,service_sent,seating_sent,price_sent,parking_sent,location_sent,alcohol_sent,coffee_sent,food_sent,hours_sent,internet_sent,local_sent
0,The Factory - Cafe With a Soul,11/25/2016 1 check-in Love love loved the vibe...,5.0 star rating,5,HIGH,1,4,3,0,0,0,0,0,0,1,3,0,0.0,0,0
1,The Factory - Cafe With a Soul,"12/2/2016 Listed in Date Night: Austin, vibe i...",4.0 star rating,4,HIGH,1,3,3,0,0,0,0,0,0,0,0,2,0.0,0,0
2,The Factory - Cafe With a Soul,11/30/2016 1 check-in Listed in food seating I...,4.0 star rating,4,HIGH,1,2,2,0,0,3,0,0,0,0,-1,2,0.0,0,0
3,The Factory - Cafe With a Soul,11/25/2016 Very cool vibe! Good drinks Nice se...,2.0 star rating,2,LOW,0,1,0,0,0,-1,-1,0,0,0,0,0,0.0,0,0
4,The Factory - Cafe With a Soul,12/3/2016 1 check-in They are location within ...,4.0 star rating,4,HIGH,1,2,0,0,0,0,0,3,0,0,0,0,0.0,0,0

In [51]:
# Change the name of the bool_HIGH column to bool_high
coffee_shop_ratings_df = coffee_shop_ratings_df.rename(columns={"bool_HIGH":"bool_high"})
coffee_shop_ratings_df.head()

,coffee_shop_name,review,rating,num_rating,cat_rating,bool_high,overall_sent,vibe_sent,tea_sent,service_sent,seating_sent,price_sent,parking_sent,location_sent,alcohol_sent,coffee_sent,food_sent,hours_sent,internet_sent,local_sent
0,The Factory - Cafe With a Soul,11/25/2016 1 check-in Love love loved the vibe...,5.0 star rating,5,HIGH,1,4,3,0,0,0,0,0,0,1,3,0,0.0,0,0
1,The Factory - Cafe With a Soul,"12/2/2016 Listed in Date Night: Austin, vibe i...",4.0 star rating,4,HIGH,1,3,3,0,0,0,0,0,0,0,0,2,0.0,0,0
2,The Factory - Cafe With a Soul,11/30/2016 1 check-in Listed in food seating I...,4.0 star rating,4,HIGH,1,2,2,0,0,3,0,0,0,0,-1,2,0.0,0,0
3,The Factory - Cafe With a Soul,11/25/2016 Very cool vibe! Good drinks Nice se...,2.0 star rating,2,LOW,0,1,0,0,0,-1,-1,0,0,0,0,0,0.0,0,0
4,The Factory - Cafe With a Soul,12/3/2016 1 check-in They are location within ...,4.0 star rating,4,HIGH,1,2,0,0,0,0,0,3,0,0,0,0,0.0,0,0

In [52]:
# Save your changes to the file as a pipe delimited file.
coffee_shop_ratings_df.to_csv('coffee_shop_ratings_df.txt', sep = '|')